name: CD

on:
  workflow_run:
    workflows: [ CI ]
    branches: [ main ]
    types: [ completed ]

jobs:
  docker:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v5
        id: meta
        env:
          # ghcr.io looks for annotations in the image index rather than platform-specific image manifests
          DOCKER_METADATA_ANNOTATIONS_LEVELS: index
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=sha
            type=ref,event=branch
            type=ref,event=tag
          # metadata-action pulls repo metadata from the REST API but GitHub doesn't detect our license 🥴
          labels: |
            org.opencontainers.image.licenses=BSD-2-Clause-Patent
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
#          outputs: type=image,name=${{ github.repository }},push=true
